language: swift
osx_image: xcode10
podfile: RestFetcherExample/Podfile

script: xcodebuild -scheme RestFetcherExample -workspace RestFetcherExample/RestFetcherExample.xcworkspace -configuration Debug clean build test -destination "platform=iOS Simulator,name=iPad Air 2,OS=latest"
