language: swift
osx_image: xcode8.3
podfile: RestFetcherExample/Podfile
branches:
  only:
    - master
before_install:
    - brew update
    - brew install xctool
script: xctool -workspace RestFetcherExample/RestFetcherExample.xcworkspace -scheme RestFetcherExample test
