language: swift
osx_image: xcode8.3
podfile: RestFetcherExample/Podfile
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=RestFetcherExample/RestFetcherExample.xcworkspace
  - IOS_FRAMEWORK_SCHEME="RestFetcherExample"
