use_frameworks!

target 'RestFetcherExample' do
    pod 'SwiftLint'
    pod 'RestFetcher', :path => '../'
    
    target 'RestFetcherExampleTests' do
        inherit! :search_paths
        
    end
end

